version : "3"

services:

  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/app
      
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWOR: example
    ports:
      - 8081:80
