version : "3"

services:

  web:
    image: webdevops/php-apache:7.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/app
      - ./php/vendor:/vendor
      - ./docker-php-ext-xdebug.ini/:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWOR: example
    ports:
      - 8081:80